apiVersion: apps/v1
kind: Deployment
metadata:
  name: secure-task-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secure-task-manager
  template:
    metadata:
      labels:
        app: secure-task-manager
    spec:
      containers:
      - name: app
        image: DOCKER_IMAGE_PLACEHOLDER
        ports:
        - containerPort: 8080
