apiVersion: apps/v1
kind: Deployment
metadata:
  name: secure-task-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secure-task-manager
  template:
    metadata:
      labels:
        app: secure-task-manager
    spec:
      containers:
        - name: secure-task-manager
          image: amanyadav207/secure-task-manager:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
