apiVersion: v1
kind: Service
metadata:
  name: secure-task-manager
spec:
  type: NodePort
  selector:
    app: secure-task-manager
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
